### PR TITLE
migrate to yarp log macros

### PR DESCRIPTION
**Pull request by nunoguedelha**
related to https://github.com/robotology/codyco-superbuild/issues/49. Migrate all print of yarp related library/modules to the new yDebug/yInfo yarp macros.

### CODE REVIEW

**Comment by traversaro** [comment]
Looks good to me, @arocchi  ?

**Comment by traversaro** [comment]
If nobody replied, I guess it is ok. Merging.

**Comment by traversaro** [comment]
Oppsss, to bold in merging, apparently there was some problem: 
https://travis-ci.org/robotology-playground/codyco-big-datasets-testing/jobs/50640604
~~~
Scanning dependencies of target paramhelp
[ 20%] Building CXX object CMakeFiles/paramhelp.dir/src/paramProxyBasic.cpp.o
[ 40%] Building CXX object CMakeFiles/paramhelp.dir/src/paramHelperBase.cpp.o
/home/travis/build/robotology-playground/codyco-superbuild/libraries/paramHelp/src/paramHelperBase.cpp: In member function ‘virtual void paramHelp::ParamHelperBase::logMsg(const string&, paramHelp::ParamHelperBase::MsgType) const’:
/home/travis/build/robotology-playground/codyco-superbuild/libraries/paramHelp/src/paramHelperBase.cpp:204:40: error: must #include <typeinfo> before using typeid
/home/travis/build/robotology-playground/codyco-superbuild/libraries/paramHelp/src/paramHelperBase.cpp:207:42: error: must #include <typeinfo> before using typeid
/home/travis/build/robotology-playground/codyco-superbuild/libraries/paramHelp/src/paramHelperBase.cpp:210:40: error: must #include <typeinfo> before using typeid
/home/travis/build/robotology-playground/codyco-superbuild/libraries/paramHelp/src/paramHelperBase.cpp:214:39: error: must #include <typeinfo> before using typeid
make[5]: *** [CMakeFiles/paramhelp.dir/src/paramHelperBase.cpp.o] Error 1
make[4]: *** [CMakeFiles/paramhelp.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [libraries/paramHelp/CMakeFiles/YCMStamp/paramHelp-build] Error 2
make[1]: *** [CMakeFiles/paramHelp.dir/all] Error 2
make: *** [all] Error 2
~~~
It seems template related, can you check @nunoguedelha ?

**Comment by nunoguedelha** [comment]
The Travis build was failing due to the wrong handling of paramHelp build dependencies. This issue was a generic issue that has been fixed in https://github.com/robotology-playground/paramHelp/pull/9.

**Pull request merged**
